[tool.poetry]
name = "newsful"
version = "0.1.0"
description = "The Backend API for Newsful - A Fact Checking Browser Plugin"
authors = [
    "Siddhesh Agarwal <siddhesh.agarwal@gmail.com>",
    "Rithik Raj <rithu0644@gmail.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
waybackpy = "^3.0.6"
fastapi = "^0.100.0"
pandas = "^2.0.3"
bert-extractive-summarizer = "^0.10.1"
torch = "^2.0.1"
nltk = "^3.8.1"
pymongo = "^4.4.1"
python-dotenv = "^1.0.0"
langchain = "^0.0.239"
uvicorn = "^0.23.1"
openai = "^0.27.8"
google-api-python-client = "^2.94.0"
scikit-learn = "1.1.2"
scipy = "1.10.0"
deep-translator = "^1.11.4"
pytesseract = "^0.3.10"
keras = "^2.13.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.7.0"

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
py_version = 310
line_length = 120
skip_glob = ["env/*"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
