[tool.poetry]
name = "newsful"
version = "0.1.0"
description = "A Fact-Checking API"
authors = ["Siddhesh Agarwal <siddhesh.agarwal@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
waybackpy = "^3.0.6"
fastapi = "^0.100.0"
pandas = "^2.0.3"
pyarrow = "^12.0.1"
bert-extractive-summarizer = "^0.10.1"
googletrans = "4.0.0rc1"
torch = "^2.0.1"
nltk = "^3.8.1"
pymongo = "^4.4.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.7.0"

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
py_version = 310
line_length = 120
skip_glob = ["env/*"]
extend_skip = [".md", ".lock", ".toml", ".csv", ".pkl"]

[tool.mypy]
python_version = 3.10
disallow_untyped_defs = true
exclude = "venv/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
